PDFA=../../utils/pdfa

pdfa:
	$(PDFA) AFM-mikroskopie-xu.pdf a/AFM-mikroskopie-xu_a.pdf
	$(PDFA) cofe-torque-sampleinfo.pdf a/cofe-torque-sampleinfo_a.pdf
	$(PDFA) ferh-memory-marti.pdf a/ferh-memory-marti_a.pdf
	$(PDFA) ferh-struktura-saidl.pdf a/ferh-struktura-saidl_a.pdf
	$(PDFA) linMOKE-silber.pdf a/linMOKE-silber_a.pdf
	$(PDFA) logo.pdf a/logo_a.pdf
	$(PDFA) mld-hystereze-kimel.pdf a/mld-hystereze-kimel_a.pdf
	$(PDFA) osmismerna-metoda-postava.pdf a/osmismerna-metoda-postava_a.pdf
	$(PDFA) osmismerna-vysledek-postava.pdf a/osmismerna-vysledek-postava_a.pdf
	$(PDFA) rotpole-metoda-liang.pdf a/rotpole-metoda-liang_a.pdf
	$(PDFA) rotpole-vysledky-liang.pdf a/rotpole-vysledky-liang_a.pdf
	$(PDFA) voigt-geometry-tesarova.pdf a/voigt-geometry-tesarova_a.pdf
	$(PDFA) vrstevnate-silber.pdf a/vrstevnate-silber_a.pdf
